export enum MaterialIconsEnum {
  menu = 'menu',
  account_circle = 'account_circle',
  arrow_downward = 'arrow_downward',
  arrow_drop_down = 'arrow_drop_down',
  bug_report = 'bug_report',
  check_circle = 'check_circle',
  close = 'close',
  cloud_circle = 'cloud_circle',
  error = 'error',
  flash_on = 'flash_on',
  info = 'info',
  language = 'language',
  more_vert = 'more_vert',
  notifications = 'notifications',
  palette = 'palette',
  signal_wifi_4_bar = 'signal_wifi_4_bar',
  signal_wifi_off = 'signal_wifi_off',
  warning = 'warning'
}
